test_that("y_linear_gaussian has the right mean and noise level", {
  set.seed(1)
  x <- matrix(rnorm(4000 * 3), 4000, 3)
  beta <- c(1, -1, 0)
  y <- y_linear_gaussian(x, beta, sigma = 2)
  expect_type(y, "double")
  expect_length(y, 4000)
  expect_equal(sd(y - x %*% beta), 2, tolerance = 0.05)
})

test_that("post_glmnet_coefs matches coef() of the cv.glmnet fit", {
  set.seed(1)
  x <- matrix(rnorm(50 * 20), 50, 20)
  beta <- c(2, -2, rep(0, 18))
  y <- y_linear_gaussian(x, beta)
  fit <- fit_cv_glmnet(x, y, nfolds = 5)
  expect_s3_class(fit, "cv.glmnet")
  out <- post_glmnet_coefs(fit, x, y, beta, s = "lambda.min")
  expect_equal(out$estimate, as.numeric(coef(fit, s = "lambda.min")))
  expect_equal(out$true_beta, c(0, beta))
  expect_equal(attr(out, "lambda"), fit$lambda.min)
  expect_error(post_glmnet_coefs(list(), x, y, beta), "cv.glmnet")
  expect_error(post_glmnet_coefs(fit, x, y, beta, s = "lambda.foo"), "not found")
})
